name: Angular CI/CD to IIS

on:
  push:
    branches: [main]   

 
    # Change if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration=production

      - name: Test SSH to IPv6 server
        run: |        
          ssh -6 -i $env:USERPROFILE\.ssh\id_ed25519 -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@[${{ secrets.SSH_HOST }}]" "echo ✅ Connected from self-hosted Windows runner!"

      # - name: Copy build files to Windows server using SCP         
      #   run: |     
      #       scp $env:USERPROFILE\.ssh\id_ed25519 -r dist/my-angular-app17/* "${{ secrets.SSH_USER }}@[${{ secrets.SSH_HOST }}]":"\"C:/inetpub/wwwroot/my-angular-app17/\""

      - name: Copy build files to Windows Server using SCP Action
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/my-angular-app17/*"
          target: "/c/inetpub/wwwroot/my-angular-app17/"        
          tar_dereference: true
          rm: true

   
   

  
      
