name: Angular CI/CD to IIS

on:
  push:
    branches: [main]   

 
    # Change if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Test SSH to IPv6 server
      run: |        
        ssh -6 -i $env:USERPROFILE\.ssh\id_ed25519 -o StrictHostKeyChecking=yes "${{ secrets.SSH_USER }}@[${{ secrets.SSH_HOST }}]" "echo ✅ Connected from self-hosted Windows runner!"

    # - name: Copy files via SSH
    #   uses: appleboy/scp-action@v1
    #   with:
    #       host: "${{ secrets.SSH_HOST }}"
    #       username: ${{ secrets.SSH_USER }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}        
    #       source: "."
    #       target: "~/inetpub"    

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '20'

    # - name: Install Dependencies
    #   run: npm install

    # - name: Build Angular App
    #   run: npm run build -- --configuration=production

  
      


    # - name: Copy files via SSH
    #   uses: appleboy/scp-action@v1
    #   with:
    #       host: ${{ '2405:204:8104:d116:5c4a:73f8:52cf:5689' }}
    #       username: ${{ 'admin' }}
    #       key: ${{ 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACBgMOb+7BJFP8Y9V4a73XDLTnsErEGjcOs9G8z5nr2VvgAAAKD1RFmq9URZqgAAAAtzc2gtZWQyNTUxOQAAACBgMOb+7BJFP8Y9V4a73XDLTnsErEGjcOs9G8z5nr2VvgAAAEAOtDuk2tMvDK1ePLY0diq0+8I31TlxUKPQYXeoLVvxS2Aw5v7sEkU/xj1XhrvdcMtOewSsQaNw6z0bzPmevZW+AAAAGGdpdGh1Yi1hY3Rpb25AYXV0b21hdGlvbgECAwQF' }}
    #       port: 22     
    #       source: "."
    #       target: "~/inetpub"

    


# jobs:
#   ssh-test:
#     runs-on: self-hosted
#     steps:
#       - name: Test SSH to IPv6 server
#         run: |
          
#           ssh -6 -i $env:USERPROFILE\.ssh\id_ed25519 -o StrictHostKeyChecking=yes "${{ secrets.SSH_USER }}@[${{ secrets.SSH_HOST }}]" "echo ✅ Connected from self-hosted Windows runner!"