name: Angular CI/CD to IIS

on:
  push:
    branches: [main]   # Change if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout Code
    #   uses: actions/checkout@v3

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '20'

    # - name: Install Dependencies
    #   run: npm install

    # - name: Build Angular App
    #   run: npm run build -- --configuration=production

    # - name: Deploy to IIS Server via SCP
    #   uses: garygrossgarten/github-action-scp@release
    #   with:
    #     local: /dist/*
    #     remote: /c$/inetpub/     
    #     host: ${{ '2405:204:8104:d116:c4a7:1179:3582:7f3b' }}
    #     username: ${{ 'admin' }}
    #     password: ${{ 'swami123' }}
      

    - name: Copy files via SSH
      uses: appleboy/scp-action@v1
      with:
          host: ${{ '2405:204:8104:d116:c4a7:1179:3582:7f3b' }}
          username: ${{ 'admin' }}
          password: ${{ 'swami123' }}
          port: ${{ '22' }}
          source: "tests/b.txt"
          target: inetpub