name: Angular CI/CD to IIS

on:
  push:
    branches: [main]   # Change if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # - name: Setup Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '20'

    # - name: Install Dependencies
    #   run: npm install

    # - name: Build Angular App
    #   run: npm run build -- --configuration=production

    # - name: Deploy to IIS Server via SCP
    #   uses: garygrossgarten/github-action-scp@release
    #   with:
    #     local: /dist/*
    #     remote: /c$/inetpub/     
    #     host: ${{ '2405:204:8104:d116:c4a7:1179:3582::7f3b' }}
    #     username: ${{ 'admin' }}
    #     password: ${{ 'swami123' }}
      


    # - name: Copy files via SSH
    #   uses: appleboy/scp-action@v1
    #   with:
    #       host: ${{ '2405:204:8104:d116:5c4a:73f8:52cf:5689' }}
    #       username: ${{ 'admin' }}
    #       key: ${{ 'b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACBgMOb+7BJFP8Y9V4a73XDLTnsErEGjcOs9G8z5nr2VvgAAAKD1RFmq9URZqgAAAAtzc2gtZWQyNTUxOQAAACBgMOb+7BJFP8Y9V4a73XDLTnsErEGjcOs9G8z5nr2VvgAAAEAOtDuk2tMvDK1ePLY0diq0+8I31TlxUKPQYXeoLVvxS2Aw5v7sEkU/xj1XhrvdcMtOewSsQaNw6z0bzPmevZW+AAAAGGdpdGh1Yi1hY3Rpb25AYXV0b21hdGlvbgECAwQF' }}
    #       port: 22     
    #       source: "."
    #       target: "~/inetpub"



   

    # - name: Copy files via SSH
    #   uses: appleboy/scp-action@v1
    #   with:
    #       host: "[${{ secrets.SSH_HOST }}]"
    #       username: ${{ secrets.SSH_USER }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}        
    #       source: "."
    #       target: "~/inetpub"

    - name: Test SSH connection over IPv6
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
    
        # Add remote host to known_hosts (without brackets)
        ssh-keyscan -6 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
        # Now test the connection (use brackets here)
        ssh -6 -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes "${{ secrets.SSH_USER }}@[${{ secrets.SSH_HOST }}]" "echo ✅ SSH connection successful!"