name: Angular CI/CD to IIS

on:
  push:
    branches: [main]   # Change if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: npm run build -- --configuration=production

    - name: Deploy to IIS Server via SCP
      uses: gohildharmik/my-angular-app17@v1.0.4
      with:
        local: dist/my-anglular-app/
        remote: \\WIN-A450TQUFJI8\my-angular-app17      
        host: ${{'103.216.81.99'}}
        username: ${{'DGOHIL'}}
        password: ${{'dmg@baps2009'}}